import type { FormState } from "./creationForm_types";

export const INITIAL_STATE: FormState = {
  national_id: "",
  national_id_issued_in: "",
  tax_id: "",
  first_name: "",
  first_surname: "",
  second_surname: "",
  date_of_birth: "",
  sex: "",
  marital_status: "",
  occupation: "",
  education_level: "",
  blood_group: "",
  primary_language: "spanish",
  indigenous_community: "",
  phone: "",
  alternative_phone: "",
  email: "",
  street: "",
  address_number: "",
  zone_neighborhood: "",
  city: "",
  state_province: "",
  reference: "",
  country: "",
  emergency_name: "",
  emergency_relationship: "",
  emergency_phone: "",
  insurance_type: "",
  insurance_affiliation_number: "",
  insurance_provider: "",
  administrative_notes: "",
}