/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as ConfigSectionRouteRouteImport } from './pages/config/$section.route'

const IndexLazyRouteImport = createFileRoute('/')()
const PatientsIndexLazyRouteImport = createFileRoute('/patients/')()
const ConfigIndexLazyRouteImport = createFileRoute('/config/')()
const BillingIndexLazyRouteImport = createFileRoute('/billing/')()
const AppointmentsIndexLazyRouteImport = createFileRoute('/appointments/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/index.lazy').then((d) => d.Route))
const PatientsIndexLazyRoute = PatientsIndexLazyRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/patients/index.lazy').then((d) => d.Route))
const ConfigIndexLazyRoute = ConfigIndexLazyRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/config/index.lazy').then((d) => d.Route))
const BillingIndexLazyRoute = BillingIndexLazyRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/billing/index.lazy').then((d) => d.Route))
const AppointmentsIndexLazyRoute = AppointmentsIndexLazyRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./pages/appointments/index.lazy').then((d) => d.Route),
)
const ConfigSectionRouteRoute = ConfigSectionRouteRouteImport.update({
  id: '/config/$section',
  path: '/config/$section',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./pages/config/$section.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/config/$section': typeof ConfigSectionRouteRoute
  '/appointments/': typeof AppointmentsIndexLazyRoute
  '/billing/': typeof BillingIndexLazyRoute
  '/config/': typeof ConfigIndexLazyRoute
  '/patients/': typeof PatientsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/config/$section': typeof ConfigSectionRouteRoute
  '/appointments': typeof AppointmentsIndexLazyRoute
  '/billing': typeof BillingIndexLazyRoute
  '/config': typeof ConfigIndexLazyRoute
  '/patients': typeof PatientsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/config/$section': typeof ConfigSectionRouteRoute
  '/appointments/': typeof AppointmentsIndexLazyRoute
  '/billing/': typeof BillingIndexLazyRoute
  '/config/': typeof ConfigIndexLazyRoute
  '/patients/': typeof PatientsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config/$section'
    | '/appointments/'
    | '/billing/'
    | '/config/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config/$section'
    | '/appointments'
    | '/billing'
    | '/config'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/config/$section'
    | '/appointments/'
    | '/billing/'
    | '/config/'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ConfigSectionRouteRoute: typeof ConfigSectionRouteRoute
  AppointmentsIndexLazyRoute: typeof AppointmentsIndexLazyRoute
  BillingIndexLazyRoute: typeof BillingIndexLazyRoute
  ConfigIndexLazyRoute: typeof ConfigIndexLazyRoute
  PatientsIndexLazyRoute: typeof PatientsIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/$section': {
      id: '/config/$section'
      path: '/config/$section'
      fullPath: '/config/$section'
      preLoaderRoute: typeof ConfigSectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ConfigSectionRouteRoute: ConfigSectionRouteRoute,
  AppointmentsIndexLazyRoute: AppointmentsIndexLazyRoute,
  BillingIndexLazyRoute: BillingIndexLazyRoute,
  ConfigIndexLazyRoute: ConfigIndexLazyRoute,
  PatientsIndexLazyRoute: PatientsIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
