/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteRouteImport } from './index.route'
import { Route as PatientsIndexRouteRouteImport } from './patients/index.route'
import { Route as BillingIndexRouteRouteImport } from './billing/index.route'
import { Route as AppointmentsIndexRouteRouteImport } from './appointments/index.route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRouteRoute = PatientsIndexRouteRouteImport.update({
  id: '/patients/',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRouteRoute = BillingIndexRouteRouteImport.update({
  id: '/billing/',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRouteRoute = AppointmentsIndexRouteRouteImport.update({
  id: '/appointments/',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/appointments/': typeof AppointmentsIndexRouteRoute
  '/billing/': typeof BillingIndexRouteRoute
  '/patients/': typeof PatientsIndexRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/appointments': typeof AppointmentsIndexRouteRoute
  '/billing': typeof BillingIndexRouteRoute
  '/patients': typeof PatientsIndexRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/appointments/': typeof AppointmentsIndexRouteRoute
  '/billing/': typeof BillingIndexRouteRoute
  '/patients/': typeof PatientsIndexRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/appointments/' | '/billing/' | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/appointments' | '/billing' | '/patients'
  id: '__root__' | '/' | '/appointments/' | '/billing/' | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AppointmentsIndexRouteRoute: typeof AppointmentsIndexRouteRoute
  BillingIndexRouteRoute: typeof BillingIndexRouteRoute
  PatientsIndexRouteRoute: typeof PatientsIndexRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AppointmentsIndexRouteRoute: AppointmentsIndexRouteRoute,
  BillingIndexRouteRoute: BillingIndexRouteRoute,
  PatientsIndexRouteRoute: PatientsIndexRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
